server:
    port: 8080
    servlet:
        context-path: /v1/api
spring:
    jpa:
        show-sql: true
springdoc:
    swagger-ui:
        path: /
    api-docs:
        path: /docs
        enabled: true

