server:
    port: 8080
    servlet:
        context-path: /v1/api
spring:
    jpa:
        show-sql: true
logging:
    level:
        org:
            springframework: off
springdoc:
    swagger-ui:
        path: index.html
    api-docs:
        path: /docs
        enabled: true

